---
matrix:
  include:
    - language: python
      install:
        - pip install -r requirements.txt
        - pip install -e .
      python: "3.6"
      script:
        - pytest
        - flake8
        - black --check --diff .
    - language: node_js
      node_js: node
      install:
        - npm install prettier
      script:
        - prettier --check .
