CREATE TABLE IF NOT EXISTS user (
  username VARCHAR(30) UNIQUE NOT NULL,
  password VARCHAR(1000) NOT NULL
);

CREATE TABLE IF NOT EXISTS user_stock (
  stock_id VARCHAR(30) NOT NULL,
  username VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS stock (
  stock_id VARCHAR(30) PRIMARY KEY,
  stock_name VARCHAR(30) NOT NULL
);
