DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS user_stock;
DROP TABLE IF EXISTS stock;

CREATE TABLE user (
  username VARCHAR(30) UNIQUE NOT NULL,
  password VARCHAR(1000) NOT NULL
);

CREATE TABLE user_stock (
  stock_id VARCHAR(30) NOT NULL,
  username VARCHAR(30) NOT NULL
);

CREATE TABLE stock (
  stock_id VARCHAR(30) PRIMARY KEY,
  stock_name VARCHAR(30) NOT NULL
);

